#!/bin/bash
#PBS -k o 
#PBS -l nodes=1:ppn=10,walltime=2:00:00:00
#PBS -l vmem=80gb
#PBS -M ffishman@iu.edu
#PBS -m abe 
#PBS -N cas_blast
#PBS -j oe 

# setup directories
slate=/N/slate/ffishman/RhizobiumDefense
out_dir=$slate/blast_output
cd $slate
fasta=$slate/output.fasta

# load required modules
module load blast/2.9.0


# blast cas genes against rhizobium 

rhizobium_id=379

if [ -d blast_output ]; then rm -r blast_output; fi
mkdir $slate/blast_output 

BLASTDP=/N/slate/ffishman/RhizobiumDefense/blastdb

time blastp -db nr -query $fasta -taxids $rhizobium_id -out $out_dir/blast.out -num_threads 10